close all, clear all, clc;

results = 'random_1.mat'; 
load(results);

figure()
subplot(4,3,1)
plot(coverageResults.polyMap.x,coverageResults.polyMap.y)
pbaspect([1 1 1])
set(gca,'visible','off')
hold on
plot(coverageResults.path25(1,:),coverageResults.path25(2,:))
pbaspect([1 1 1])
set(gca,'visible','off')
subplot(4,3,4)
plot(coverageResults.polyMap.x,coverageResults.polyMap.y)
pbaspect([1 1 1])
set(gca,'visible','off')
hold on
plot(coverageResults.path50(1,:),coverageResults.path50(2,:))
pbaspect([1 1 1])
set(gca,'visible','off')
subplot(4,3,7)
plot(coverageResults.polyMap.x,coverageResults.polyMap.y)
pbaspect([1 1 1])
set(gca,'visible','off')
hold on
plot(coverageResults.path75(1,:),coverageResults.path75(2,:))
pbaspect([1 1 1])
set(gca,'visible','off')
subplot(4,3,10)
plot(coverageResults.polyMap.x,coverageResults.polyMap.y)
pbaspect([1 1 1])
set(gca,'visible','off')
hold on
plot(coverageResults.path(1,:),coverageResults.path(2,:))
pbaspect([1 1 1])
set(gca,'visible','off')

subplot(4,3,2)
surf(coverageResults.coverageMap25')
pbaspect([1 1 1])
set(gca,'visible','off')
subplot(4,3,5)
surf(coverageResults.coverageMap50')
pbaspect([1 1 1])
set(gca,'visible','off')
subplot(4,3,8)
surf(coverageResults.coverageMap75')
pbaspect([1 1 1])
set(gca,'visible','off')
subplot(4,3,11)
surf(coverageResults.coverageMap')
pbaspect([1 1 1])
set(gca,'visible','off')

subplot(4,3,3)
surf(coverageResults.groundTruth25')
pbaspect([1 1 1])
set(gca,'visible','off')
subplot(4,3,6)
surf(coverageResults.groundTruth50')
pbaspect([1 1 1])
set(gca,'visible','off')
subplot(4,3,9)
surf(coverageResults.groundTruth75')
pbaspect([1 1 1])
set(gca,'visible','off')
subplot(4,3,12)
surf(coverageResults.groundTruth')
pbaspect([1 1 1])
set(gca,'visible','off')